
spring:
  # 数据源配置
  datasource:
      url: jdbc:mysql://localhost:3306/store?autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: ab12
      driverClassName: com.mysql.jdbc.Driver
      
  # 配置直接访问templates下的html
  resources:    static-locations: classpath:/static,classpath:/templates  
  # mvc相关配置
  mvc:      view:        prefix: /WEB-INF/views/        suffix: .jsp
        
  # 日志
  output: 
    ansi:      enabled: always

# 配置扫描路径    mybatis:  mapper-locations: classpath:/mapper/**/*Mapper.xml    
  
# 工程配置 
server:
    servlet: 
      # 访问路径
      context-path: /
       # 访问端口
    port: 8081 
      
# 自定义的一些属性      
app:
  name: 丝绸之路
  version: 1.0
  copyright: 2019
  
user:
  cookie: 
    name: shop-demo-cookie
    age: 86400
    
  