
spring:
  # 数据源配置
  datasource:
      url: jdbc:mysql://192.168.1.94:3306/ayg_test?autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
      
  # 配置直接访问templates下的html
  resources:    static-locations: classpath:/static,classpath:/templates  
  # mvc相关配置
  mvc:      view:        prefix: /WEB-INF/views/        suffix: .jsp
        
  # 日志
  output: 
    ansi:      enabled: always
     
  # redis配置
  redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      timeout: 10000  # 连接超时时长（毫秒）
      jedis:
        pool:
          max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 10      # 连接池中的最大空闲连接
          min-idle: 5       # 连接池中的最小空闲连接

# 配置扫描路径    mybatis:  mapper-locations: classpath:/mapper/**/*Mapper.xml    
  
# 工程配置 
server:
    servlet: 
      # 访问路径
      context-path: /
       # 访问端口
    port: 8081 
      
# 自定义的一些属性      
app:
  name: 丝绸之路
  version: 1.0
  copyright: 2019
  
user:
  cookie: 
    name: shop-demo-cookie
    age: 86400
    
  